dataset:
  metadata: /mnt/cephfs/mir/jcaicedo/morphem/dataset/sampling/multi_channel_chammi_metadata.csv
train:
  name: ""
  data_path: /scr/data/CHAMMI/chammi_train.zip
  output_dir: /scr/data/channel_vit_models/testing