_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
accum_iter:
    value: 1
batch_size:
    value: 1024
blr:
    value: 0.001
data_path:
    value: /scr/vidit/chammi_train.zip
device:
    value: cuda
dist_backend:
    value: nccl
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: true
epochs:
    value: 400
gpu:
    value: 0
input_size:
    value: 224
local_rank:
    value: 0
log_dir:
    value: ./output_dir
lr:
    value: 5e-05
mask_ratio:
    value: 0.75
min_lr:
    value: 0
model:
    value: mae_vit_small_patch16
norm_pix_loss:
    value: false
num_workers:
    value: 12
output_dir:
    value: /scr/vidit/Models/CHAMMI_3_set
pin_mem:
    value: true
rank:
    value: 0
resume:
    value: ""
seed:
    value: 0
start_epoch:
    value: 0
warmup_epochs:
    value: 40
weight_decay:
    value: 0.05
world_size:
    value: 8
