name: weakly-supervised
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake
  - pip
  - cellpose=3.0.11
  - polars-lts-cpu=1.22.0
  - safetensors=0.5.2
  - scikit-image=0.25.2
  - scikit-learn=1.6.1
  - pandas
  - fastai::opencv-python-headless
  - bioconda::snakemake-minimal=8.16.0
  - pip:
      - htcondor
      - huggingface-hub==0.29.3
      - transformers==4.45.1 
      - omegaconf==2.3.0
      - timm==1.0.15
      - git+https://github.com/jhiemstrawisc/snakemake-executor-plugin-htcondor.git@shared-and-non-shared  
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.5.1+cu118
      - torchvision
