student:
  arch: vit_small
  patch_size: 14
  num_register_tokens: 4
  interpolate_antialias: true
  interpolate_offset: 0.0
  in_chans: 4
crops:
  # todo: try crop sizes of 112, 56. Or try changing the input timage size to match 518.
  global_crops_size: 518  # this is to set up the position embeddings properly
  local_crops_size: 98