wandb_version: 1

model:
  desc: null
  value:
    arch: Arch.channelvit_small
    patch_size: 16
    out_dim: 65536
    norm_last_layer: true
    momentum_teacher: 0.996
    use_bn_in_head: false
temp:
  desc: null
  value:
    warmup_teacher_temp: 0.04
    teacher_temp: 0.04
    warmup_teacher_temp_epochs: 0
optim:
  desc: null
  value:
    use_fp16: true
    weight_decay: 0.04
    weight_decay_end: 0.4
    clip_grad: 3.0
    batch_size_per_gpu: 32
    epochs: 100
    freeze_last_layer: 1
    lr: 5.0e-05
    warmup_epochs: 10
    min_lr: 1.0e-06
    optimizer: adamw
    drop_path_rate: 0.1
crops:
  desc: null
  value:
    global_crops_scale:
    - 0.4
    - 1.0
    local_crops_number: 8
    local_crops_scale:
    - 0.05
    - 0.4
dataset:
  desc: null
  value:
    guided_crops_path: null
    dataset_size: DatasetSize.large
    multiscale: false
    guided_cropping: false
    guided_crops_size:
    - 256
    - 256
    small_list_path: null
    metadata: /mnt/cephfs/mir/jcaicedo/morphem/dataset/sampling/multi_channel_chammi_metadata.csv
train:
  desc: null
  value:
    name: wandb_test
    data_path: /scr/data/CHAMMI/chammi_train.zip
    output_dir: /mnt/cephfs/mir/jcaicedo/projects/channel_vit_dinov1/models/wandb_test
    saveckp_freq: 20
    seed: 42
    num_workers: 10
    dist_url: env://
    local_rank: 0
    world_size: 7
    gpu: 0
    rank: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1755267108.618863
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.8
      8:
      - 5
